title: Scientists4Future Dortmund
email: your-email@example.com
description: >- # this means to ignore newlines until the next item
    Homepage der Dortmunder Lokalgruppe Scientists4Future
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  s4f-dortmund

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
